=== gfruleux/ofbiz-framework/framework/widget/dtd/widget-theme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns="http://ofbiz.apache.org/Widget-Theme" targetNamespace="http://ofbiz.apache.org/Widget-Theme">
    <xs:element name="theme">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="1" ref="visual-themes"/>
                <xs:element minOccurs="0" maxOccurs="1" ref="extends"/>
                <xs:element minOccurs="0" maxOccurs="1" ref="widget-properties"/>
                <xs:element minOccurs="0" maxOccurs="1" ref="theme-properties"/>
                <xs:element minOccurs="0" maxOccurs="1" ref="templates"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="visual-themes">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="visual-theme" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="visual-theme">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="1" ref="description" />
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="screenshot" />
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="required" />
            <xs:attribute type="xs:string" name="display-name" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:element name="description"/>
    <xs:element name="screenshot">
        <xs:complexType>
            <xs:attribute type="xs:string" name="location" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:element name="extends">
        <xs:complexType>
            <xs:attribute type="xs:string" name="location" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:element name="widget-properties">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="default-view-size">
                    <xs:complexType>
                        <xs:attribute type="xs:integer" name="value" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="autocompleter">
                    <xs:complexType>
                        <xs:attribute type="xs:integer" name="default-view-size" />
                        <xs:attribute type="xs:integer" name="default-min-lenght" />
                        <xs:attribute type="xs:integer" name="default-delay" />
                        <xs:attribute name="display-return-field">
                            <xs:simpleType>
                                <xs:restriction base="xs:token">
                                    <xs:enumeration value="true" />
                                    <xs:enumeration value="false" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="lookup">
                    <xs:complexType>
                        <xs:attribute type="xs:integer" name="height" />
                        <xs:attribute type="xs:integer" name="width" />
                        <xs:attribute name="position">
                            <xs:simpleType>
                                <xs:restriction base="xs:token">
                                    <xs:enumeration value="top-left"/>
                                    <xs:enumeration value="top-right"/>
                                    <xs:enumeration value="bottom-left"/>
                                    <xs:enumeration value="bottom-right"/>
                                    <xs:enumeration value="center"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="layered-modal">
                    <xs:complexType>
                        <xs:attribute type="xs:integer" name="height" />
                        <xs:attribute type="xs:integer" name="width" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="theme-properties">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="property" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="property">
        <xs:complexType>
            <xs:attribute type="xs:string" name="name" use="required" />
            <xs:attribute type="xs:string" name="value" use="required" />
            <xs:attribute type="xs:string" name="type" />
        </xs:complexType>
    </xs:element>
    <xs:element name="templates">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="template" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="template">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="4" ref="template-file" />
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required" />
            <xs:attribute type="xs:string" name="type" use="required"/>
            <xs:attribute type="xs:string" name="encoding" />
            <xs:attribute type="xs:string" name="content-type" />
            <xs:attribute type="xs:string" name="encoder" />
            <xs:attribute name="compress">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="true" />
                        <xs:enumeration value="false" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="template-file">
    <xs:complexType>
        <xs:attribute type="xs:string" name="widget" use="required" >
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="screen" />
                    <xs:enumeration value="form" />
                    <xs:enumeration value="tree" />
                    <xs:enumeration value="menu" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="location" use="required"/>
    </xs:complexType>
    </xs:element>
    <xs:element name="common-screens">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="1" ref="root-decorator" />
                <xs:element minOccurs="0" maxOccurs="1" ref="subtype-decorator" />
                <xs:element minOccurs="0" maxOccurs="1" ref="generic-screen" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="root-decorator">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="screen" />
            </xs:sequence>
            <xs:attribute type="xs:string" name="default-location" use="optional" />
        </xs:complexType>
    </xs:element>
    <xs:element name="subtype-decorator">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="screen" />
            </xs:sequence>
            <xs:attribute type="xs:string" name="default-location" use="optional" />
        </xs:complexType>
    </xs:element>
    <xs:element name="generic-screen">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="screen" />
            </xs:sequence>
            <xs:attribute type="xs:string" name="default-location" use="optional" />
        </xs:complexType>
    </xs:element>
    <xs:element name="screen">
        <xs:complexType>
            <xs:attribute type="xs:string" name="name" use="required"/>
            <xs:attribute type="xs:string" name="location" use="optional"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== gfruleux/ofbiz-framework/themes/common/widget/Theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->

<theme name="common"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://ofbiz.apache.org/dtds/widget-theme.xsd">
    <visual-themes><!--List of visual theme contains to this theme components-->
        <visual-theme id="COMMON"/>
    </visual-themes>
    <widget-properties><!--Transversal properties relative to ofbiz widget component-->
        <default-view-size value="20"/>
        <autocompleter
                default-view-size="10"
                default-min-lenght="2"
                default-delay="300"
                display-return-field="true"/>
        <lookup
                position="topleft"
                width="640"
                height="500"/>
        <layered-modal
                width="800"
                height="600"/>
    </widget-properties>

    <theme-properties> <!--specific properties dedicate to this theme -->
        <property name="jgrowl.position" value="center" type="String"/><!--possible value: top-left, top-right, bottom-left, bottom-right, center-->
        <property name="jgrowl.width" value="800" type="Integer"/>
        <property name="jgrowl.height" value="" type="Integer"/>
        <property name="jgrowl.speed" value="100" type="Integer"/>
    </theme-properties>

    <templates><!-- Freemarker template use by this theme to render widget model-->
        <template name="screen" type="html" content-type="UTF-8" encoding="none" encoder="html" compress="false">
            <template-file widget="screen" location="component://common-theme/template/macro/HtmlScreenMacroLibrary.ftl"/>
            <template-file widget="form" location="component://common-theme/template/macro/HtmlFormMacroLibrary.ftl"/>
            <template-file widget="tree" location="component://common-theme/template/macro/HtmlTreeMacroLibrary.ftl"/>
            <template-file widget="menu" location="component://common-theme/template/macro/HtmlMenuMacroLibrary.ftl"/>
        </template>
        <template name="screenxml" type="xml" content-type="UTF-8" encoding="none" encoder="xml">
            <template-file widget="screen" location="component://common-theme/template/macro/XmlScreenMacroLibrary.ftl"/>
            <template-file widget="form" location="component://common-theme/template/macro/XmlFormMacroLibrary.ftl"/>
            <template-file widget="tree" location="component://common-theme/template/macro/XmlTreeMacroLibrary.ftl"/>
        </template>
        <template name="screenxls" type="xls" content-type="application/vnd.ms-excel" encoding="none" encoder="html">
            <template-file widget="screen" location="component://common-theme/template/macro/XlsScreenMacroLibrary.ftl"/>
            <template-file widget="form" location="component://common-theme/template/macro/XlsFormMacroLibrary.ftl"/>
            <template-file widget="tree" location="component://common-theme/template/macro/XlsTreeMacroLibrary.ftl"/>
        </template>
        <template name="screenfop" type="xsl-fo" content-type="application/pdf" encoding="none">
            <template-file widget="screen" location="component://common-theme/template/macro/FoScreenMacroLibrary.ftl"/>
            <template-file widget="form" location="component://common-theme/template/macro/FoFormMacroLibrary.ftl"/>
            <template-file widget="tree" location="component://common-theme/template/macro/FoTreeMacroLibrary.ftl"/>
        </template>
        <template name="screentext" type="text" content-type="UTF-8" encoding="none">
            <template-file widget="screen" location="component://common-theme/template/macro/TextScreenMacroLibrary.ftl"/>
            <template-file widget="form" location="component://common-theme/template/macro/TextFormMacroLibrary.ftl"/>
            <template-file widget="tree" location="component://common-theme/template/macro/TextTreeMacroLibrary.ftl"/>
        </template>
        <template name="screencsv" type="csv" content-type="UTF-8" encoding="none" encoder="xml">
            <template-file widget="screen" location="component://common-theme/template/macro/CsvScreenMacroLibrary.ftl"/>
            <template-file widget="form" location="component://common-theme/template/macro/CsvFormMacroLibrary.ftl"/>
            <template-file widget="tree" location="component://common-theme/template/macro/CsvTreeMacroLibrary.ftl"/>
        </template>
    </templates>

    <common-screens><!--list all common screen and decorator global to each application that each theme can be surcharge or not and use the screen present on common theme-->
        <structural-decorator default-location="component://common-theme/widget/CommonScreens.xml">
            <screen name="AjaxGlobalDecorator"/>
            <screen name="ajaxAutocompleteOptions"/>
            <screen name="GlobalActions"/>
            <screen name="GlobalDecorator"/>
            <screen name="LookupDecorator"/>
            <screen name="SimpleDecorator"/>
            <screen name="FoReportDecorator"/>
            <screen name="GlobalFoDecorator"/>
        </structural-decorator>
        <embed-decorator default-location="component://common-theme/widget/CommonEmbedScreens.xml">
            <screen name="FindScreenDecorator"/>
        </embed-decorator>
        <general-screen default-location="component://common-theme/widget/CommonDedicateScreens.xml">
            <screen name="geoChart"/>
            <screen name="EventMessages"/>
            <screen name="countries"/>
            <screen name="states"/>
            <screen name="cctypes"/>
            <screen name="ccmonths"/>
            <screen name="ccyears"/>
            <screen name="genericLink"/>
            <screen name="ajaxAutocompleteOptions"/>
            <screen name="FoError"/>
            <screen name="login"/>
            <screen name="ajaxNotLoggedIn"/>
            <screen name="requirePasswordChange"/>
            <screen name="forgotPassword_step1"/>
            <screen name="forgotPassword_step2"/>
            <screen name="forgotPassword"/>
            <screen name="help"/>
            <screen name="viewBlocked"/>
        </general-screen>
    </common-screens>
</theme>

=== gfruleux/ofbiz-framework/themes/common/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->

<theme name="common"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://ofbiz.apache.org/dtds/widget-theme.xsd">
    <visual-themes>
        <visual-theme id="COMMON"/>
    </visual-themes>
    <default-view-size value="20"/>
    <autocompleter
            default-view-size="10"
            default-min-lenght="2"
            default-delay="300"
            display-return-field="true"/>
    <lookup
            position="topleft"
            width="640"
            height="500"/>
    <layered-modal
            width="800"
            height="600"/>
    <properties>
        <property name="jgrowl.position" value="center" type="String"/><!--possible value: top-left, top-right, bottom-left, bottom-right, center-->
        <property name="jgrowl.width" value="800" type="Integer"/>
        <property name="jgrowl.height" value="" type="Integer"/>
        <property name="jgrowl.speed" value="100" type="Integer"/>
    </properties>

    <templates>
        <template name="screen" type="html" content-type="UTF-8" encoding="none" encoder="html" compress="false">
            <template-file widget="screen" location="component://common-theme/template/macro/HtmlScreenMacroLibrary.ftl"/>
            <template-file widget="form" location="component://common-theme/template/macro/HtmlFormMacroLibrary.ftl"/>
            <template-file widget="tree" location="component://common-theme/template/macro/HtmlTreeMacroLibrary.ftl"/>
            <template-file widget="menu" location="component://common-theme/template/macro/HtmlMenuMacroLibrary.ftl"/>
        </template>
        <template name="screenxml" type="xml" content-type="UTF-8" encoding="none" encoder="xml">
            <template-file widget="screen" location="component://common-theme/template/macro/XmlScreenMacroLibrary.ftl"/>
            <template-file widget="form" location="component://common-theme/template/macro/XmlFormMacroLibrary.ftl"/>
            <template-file widget="tree" location="component://common-theme/template/macro/XmlTreeMacroLibrary.ftl"/>
        </template>
        <template name="screenxls" type="xls" content-type="application/vnd.ms-excel" encoding="none" encoder="html">
            <template-file widget="screen" location="component://common-theme/template/macro/XlsScreenMacroLibrary.ftl"/>
            <template-file widget="form" location="component://common-theme/template/macro/XlsFormMacroLibrary.ftl"/>
            <template-file widget="tree" location="component://common-theme/template/macro/XlsTreeMacroLibrary.ftl"/>
        </template>
        <template name="screenfop" type="xsl-fo" content-type="application/pdf" encoding="none">
            <template-file widget="screen" location="component://common-theme/template/macro/FoScreenMacroLibrary.ftl"/>
            <template-file widget="form" location="component://common-theme/template/macro/FoFormMacroLibrary.ftl"/>
            <template-file widget="tree" location="component://common-theme/template/macro/FoTreeMacroLibrary.ftl"/>
        </template>
        <template name="screentext" type="text" content-type="UTF-8" encoding="none">
            <template-file widget="screen" location="component://common-theme/template/macro/TextScreenMacroLibrary.ftl"/>
            <template-file widget="form" location="component://common-theme/template/macro/TextFormMacroLibrary.ftl"/>
            <template-file widget="tree" location="component://common-theme/template/macro/TextTreeMacroLibrary.ftl"/>
        </template>
        <template name="screencsv" type="csv" content-type="UTF-8" encoding="none" encoder="xml">
            <template-file widget="screen" location="component://common-theme/template/macro/CsvScreenMacroLibrary.ftl"/>
            <template-file widget="form" location="component://common-theme/template/macro/CsvFormMacroLibrary.ftl"/>
            <template-file widget="tree" location="component://common-theme/template/macro/CsvTreeMacroLibrary.ftl"/>
        </template>
    </templates>

</theme>

=== gfruleux/ofbiz-framework/themes/flatgrey/widget/Theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->

<theme name="flatgrey"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://ofbiz.apache.org/dtds/widget-theme.xsd">
    <visual-themes>
        <visual-theme id="FLAT_GREY" display-name="Flat Grey">
            <description>Floating Layout, Sight-Impaired Accessible, Bidirectional</description>
            <screenshot location="/flatgrey/screenshot.jpg"/>
        </visual-theme>
    </visual-themes>
    <extends location="component://common-theme/widget/Theme.xml"/>

    <theme-properties>
        <!--template location-->
        <property name="VT_HDR_IMAGE_URL" value="/flatgrey/images/ofbiz_logo.gif"/>
        <!--javascript lib-->
        <property name="VT_HDR_JAVASCRIPT[+0]" value="/flatgrey/js/application.js"/>
        <!--Css style-->
        <property name="VT_STYLESHEET[+0]" value="/flatgrey/style.css"/>
        <property name="VT_STYLESHEET[+0]" value="/flatgrey/javascript.css"/>
        <property name="VT_HELPSTYLESHEET[]" value="/flatgrey/help.css"/>
        <property name="VT_DOCBOOKSTYLESHEET[]" value="/flatgrey/webapp/flatgrey/docbook.css"/>
        <property name="VT_RTL_STYLESHEET[]" value="/flatgrey/stylertl.css"/>
    </theme-properties>

</theme>
